image:
  name: yusufbarisk/mudegrader
  entrypoint: [""]

variables:
  POSTGRES_HOST_AUTH_METHOD: trust
  ENV: CI
  GITLAB_PRIVATE_TOKEN: glpat-ax4-Nz3LAkBJDJdSW44H
  GLOBAL_GROUP_ID: 35312
  GITLAB_URL: https://gitlab.tudelft.nl/
  LOGGER_NAMESPACE: mudegrader.gitlabmanager



# List of stages for jobs, and their order of execution
stages:
  - lint
  - test
  - build_deploy

before_script:
  - pwd
  - python --version
  - ls -la
  - pip install -r ./requirements.txt
  - cat ./mudegrader/prospector.yml
  - python ./mudegrader/manage.py makemigrations

prospector:
  stage: lint
  script:
    - echo "Executing Prospector..."
    - prospector --profile-path ./mudegrader/prospector.yml || true

unittest:
  stage: test
  services:
    - postgres:16-bullseye
  script:
    - export DJANGO_SETTINGS_MODULE=mudegrader.settings
    - coverage run ./mudegrader/manage.py test assignment_manager gitlabmanager graderandfeedbacktool analytics services authentication
    - coverage report
    - coverage xml -o coverage.xml
    - coverage-badge -o coverage.svg
  artifacts:
    paths:
      - coverage.xml
      - coverage.svg
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

# build_deploy:
#   stage: build_deploy
#   script:
#     - echo "Installing Docker..."
#     - apt-get update
#     - apt-get install -y docker.io  # Install Docker
#     - echo "Installing Docker Compose..."
#     - apt-get update
#     - apt-get install -y docker-compose  # Install Docker Compose
#     - export PATH="$PATH:/usr/local/bin"
#     - which docker-compose
#     - service docker start
#     - echo "Creating .env file..."
#     - echo "GITLAB_PRIVATE_TOKEN=$GITLAB_PRIVATE_TOKEN" > .env
#     - echo "GLOBAL_GROUP_ID=35312" >> .env
#     - echo "POSTGRES_USER=$POSTGRES_USER" >> .env
#     - echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
#     - echo "POSTGRES_DB=$POSTGRES_DB" >> .env
#     - echo "PGADMIN_DEFAULT_EMAIL=$PGADMIN_DEFAULT_EMAIL" >> .env
#     - echo "PGADMIN_DEFAULT_PASSWORD=$PGADMIN_DEFAULT_PASSWORD" >> .env
#     - echo "Building Docker image..."
#     - docker-compose build
#     - echo "Tagging Docker image..."
#     - docker tag mude-grader_web:latest mshomis/mudegrader:test-version
#     - echo "Logging in to Docker registry..."
#     - echo "dckr_pat_NZM9G9vaR8fYPzH0b7x9wW6h_Vs" | docker login -u "mshomis" --password-stdin
#     - echo "Pushing Docker image..."
#     - docker push mshomis/mudegrader:test-version

#   only:
#     - main

